baseURL = 'https://example.com/'
languageCode = 'zh-cn'
title = '我的博客'
theme = 'simpleblue'

# 分页设置
paginate = 10
summaryLength = 30

# 启用KaTeX渲染数学公式
[params]
katex = true
# 设置主要文章类型 - 这很重要，归档功能依赖此设置
mainSections = ["posts", "blog", "post"]
# 是否显示上一篇/下一篇文章导航
showPostNavigation = true
# 站点描述
description = "我的个人博客和日记"

# 主菜单配置
[menu]
[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 10
[[menu.main]]
identifier = "archive"
name = "归档"
url = "/archive/"
weight = 20
[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 30
[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 40
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 50

[permalinks]
posts = "/:year/:month/:slug/"

# 归档页面内容生成（必需）
[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

# 默认值，确保文章都有正确的参数
[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
