baseURL = 'https://example.com/'
languageCode = 'zh-cn'
title = '我的博客'
theme = 'simpleblue'

# 主菜单配置
[menu]
[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 10
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 20
[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 30
[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 40
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 50

[params]
# 设置主要文章类型
mainSections = ["posts", "blog", "diary"]

# 是否显示上一篇/下一篇文章导航
showPostNavigation = true

# 每页显示的文章数量
paginate = 5

# 站点描述
description = "我的个人博客和日记"

[permalinks]
posts = "/:year/:month/:slug/"
