baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "我的个人博客"
theme = "simpleblue"

# 主要内容所在的部分
[params]
description = "个人知识整理与记录"
mainSections = ["posts"]
katex = true              # 启用KaTeX数学公式

# 分页设置 (更新为新的配置项)
[params.pagination]
pagerSize = 10

# 避免RSS生成
[outputs]
home = ["HTML", "JSON"] # 添加JSON输出用于搜索功能
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

# 菜单配置
[menu]
[[menu.main]]
name = "首页"
url = "/"
weight = 1
[[menu.main]]
name = "归档"
url = "/archives/"
weight = 2
[[menu.main]]
name = "分类"
url = "/categories/"
weight = 3
[[menu.main]]
name = "标签"
url = "/tags/"
weight = 4

# URL设置 - 确保只有一个 permalinks 部分
[permalinks]
posts = "/:year/:month/:slug/"
archives = "/archives/"

# 语法高亮
[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "github"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true # 允许在Markdown中使用原始HTML
