name = "SimpleBlue"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-simpleblue/LICENSE"
description = "A simple blue and white theme with KaTeX support"
homepage = "https://github.com/yourusername/hugo-simpleblue"
tags = ["blog", "responsive", "light", "mathematics", "katex", "clean"]
features = ["responsive", "katex", "blog", "clean"]
min_version = "0.60.0"

[author]
name = "Your Name"
homepage = "https://yourdomain.com"
